'use client';

import React from 'react';
import {
  ShieldCheck,
  ShieldAlert,
  Zap,
  Activity,
  CheckCircle,
  AlertTriangle,
  FileCheck,
  Sparkles,
  Award,
  Check,
  AlertCircle,
  ExternalLink,
} from 'lucide-react';

export interface ScoreMetric {
  name: string;
  score: number;
  weight?: number;
  status: 'passed' | 'warning' | 'failed';
  details?: string;
}

export interface QodoScorecardProps {
  overallScore?: number;
  grade?: string;
  verdict?: string;
  metrics?: {
    codeQuality?: ScoreMetric;
    security?: ScoreMetric;
    testCoverage?: ScoreMetric;
    performance?: ScoreMetric;
  };
  keyFindings?: string[];
  securityFindings?: Array<{
    severity: string;
    title: string;
    description: string;
    mitigated: boolean;
  }>;
  reviewComments?: Array<{
    file: string;
    lineNumber: number;
    comment: string;
    type: string;
  }>;
}

export const QodoScorecard: React.FC<QodoScorecardProps> = ({
  overallScore = 96,
  grade = 'A+',
  verdict = 'APPROVED_FOR_PR',
  metrics,
  keyFindings = [],
  securityFindings = [],
  reviewComments = [],
}) => {
  const quality = metrics?.codeQuality || {
    name: 'Code Quality',
    score: 95,
    status: 'passed' as const,
    details: 'Minimal diff (+4, -2 lines), low cyclomatic complexity (2), zero dead code',
  };

  const security = metrics?.security || {
    name: 'Security Audit',
    score: 100,
    status: 'passed' as const,
    details: 'Zero AST taint paths, zero hardcoded credentials, strict input validation',
  };

  const coverage = metrics?.testCoverage || {
    name: 'Test Coverage',
    score: 92,
    status: 'passed' as const,
    details: 'Patched branches covered by 3 unit tests generated by Qodo Cover',
  };

  const performance = metrics?.performance || {
    name: 'Performance',
    score: 98,
    status: 'passed' as const,
    details: 'O(1) constant time overhead, zero unbounded memory allocations',
  };

  const metricList = [quality, security, coverage, performance];

  const getScoreColor = (score: number) => {
    if (score >= 90) return 'text-emerald-400 border-emerald-500/50 bg-emerald-950/40';
    if (score >= 75) return 'text-cyan-400 border-cyan-500/50 bg-cyan-950/40';
    if (score >= 60) return 'text-amber-400 border-amber-500/50 bg-amber-950/40';
    return 'text-rose-400 border-rose-500/50 bg-rose-950/40';
  };

  const getProgressBarColor = (score: number) => {
    if (score >= 90) return 'bg-emerald-400';
    if (score >= 75) return 'bg-cyan-400';
    if (score >= 60) return 'bg-amber-400';
    return 'bg-rose-400';
  };

  return (
    <div className="flex h-full flex-col rounded-xl bg-zinc-900/70 border border-zinc-800/80 backdrop-blur-md p-4">
      {/* Scorecard Header */}
      <div className="flex items-center justify-between border-b border-zinc-800/80 pb-3 mb-4">
        <div className="flex items-center space-x-2">
          <Sparkles className="h-4 w-4 text-cyan-400" />
          <h2 className="text-sm font-semibold font-mono text-white tracking-wide">
            Qodo PR-Agent Quality & Security Scorecard
          </h2>
        </div>
        <span className="rounded bg-cyan-500/10 border border-cyan-500/30 px-2 py-0.5 text-[11px] font-mono text-cyan-300 font-bold">
          {verdict.replace(/_/g, ' ')}
        </span>
      </div>

      {/* Composite Score Summary Gauge */}
      <div className="flex flex-wrap items-center justify-between rounded-xl bg-zinc-950/70 border border-zinc-800 p-4 mb-4 gap-4">
        <div className="flex items-center space-x-4">
          {/* Radial Score Circle */}
          <div className="relative flex h-16 w-16 items-center justify-center rounded-2xl bg-zinc-900 border border-cyan-500/40 glow-cyan">
            <span className="text-xl font-black font-mono text-cyan-300">{overallScore}</span>
            <span className="absolute -bottom-1 -right-1 flex h-6 w-6 items-center justify-center rounded-full bg-cyan-500 font-mono text-[10px] font-bold text-zinc-950">
              {grade}
            </span>
          </div>

          <div>
            <div className="flex items-center space-x-2">
              <span className="text-sm font-bold font-mono text-white">
                Composite Score: {overallScore}/100
              </span>
            </div>
            <p className="text-xs text-zinc-400 font-mono mt-0.5">
              Formula: 0.35Q + 0.35S + 0.20C + 0.10P
            </p>
          </div>
        </div>

        <div className="flex items-center space-x-2 text-xs font-mono">
          <div className="rounded-lg bg-emerald-950/80 border border-emerald-600/60 px-3 py-1.5 text-emerald-300 flex items-center space-x-1.5">
            <CheckCircle className="h-3.5 w-3.5 text-emerald-400" />
            <span>Security: Clean Pass</span>
          </div>
        </div>
      </div>

      {/* 4 Metric Dimension Bars */}
      <div className="space-y-3 mb-4">
        {metricList.map((m) => (
          <div key={m.name} className="rounded-lg bg-zinc-950/50 border border-zinc-800/80 p-2.5">
            <div className="flex items-center justify-between text-xs font-mono mb-1.5">
              <span className="text-zinc-300 font-medium">{m.name}</span>
              <span className={`px-2 py-0.5 rounded border text-[11px] font-bold ${getScoreColor(m.score)}`}>
                {m.score}/100
              </span>
            </div>

            {/* Progress Track */}
            <div className="h-1.5 w-full rounded-full bg-zinc-800 overflow-hidden mb-1.5">
              <div
                className={`h-full rounded-full transition-all duration-500 ${getProgressBarColor(m.score)}`}
                style={{ width: `${m.score}%` }}
              />
            </div>

            {m.details && (
              <p className="text-[11px] text-zinc-400 font-mono truncate">
                {m.details}
              </p>
            )}
          </div>
        ))}
      </div>

      {/* Security Audit Findings & Review Notes */}
      <div className="flex-1 overflow-y-auto space-y-2">
        <h4 className="text-xs font-mono font-semibold uppercase tracking-wider text-zinc-400">
          Security & AST Findings
        </h4>
        {securityFindings.length > 0 ? (
          securityFindings.map((f, i) => (
            <div
              key={i}
              className={`rounded-lg border p-2 text-xs font-mono flex items-start space-x-2 ${
                f.mitigated
                  ? 'bg-emerald-950/30 border-emerald-800/60 text-emerald-300'
                  : 'bg-rose-950/30 border-rose-800/60 text-rose-300'
              }`}
            >
              {f.mitigated ? (
                <Check className="h-4 w-4 shrink-0 text-emerald-400 mt-0.5" />
              ) : (
                <AlertCircle className="h-4 w-4 shrink-0 text-rose-400 mt-0.5" />
              )}
              <div className="flex-1 min-w-0">
                <div className="font-semibold">{f.title}</div>
                <div className="text-[11px] text-zinc-400">{f.description}</div>
              </div>
            </div>
          ))
        ) : (
          <div className="rounded-lg border border-zinc-800/80 bg-zinc-950/40 p-2.5 text-xs font-mono text-zinc-400 flex items-center space-x-2">
            <ShieldCheck className="h-4 w-4 text-emerald-400 shrink-0" />
            <span>Zero CWE/CVE security vulnerabilities detected in AST analysis.</span>
          </div>
        )}
      </div>
    </div>
  );
};
export default QodoScorecard;
